name: Update stats

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: erlef/setup-beam@v1
      with:
        otp-version: "25"
        elixir-version: "1.14.0"
    - uses: actions/checkout@v3
    - run: elixir stats.exs
      env:
        AOC_SESSION: ${{ secrets.AOC_SESSION }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate stats table in README
        branch: ${{ github.head_ref }}
